baseURL = "https://berita.edueasy.id/"
languageCode = "id"
title = "eduEasy Berita"
defaultContentLanguage = "id"

# Module Tema
[module]
  [[module.imports]]
    path = "github.com/CaiJimmy/hugo-theme-stack/v3"

# Pengaturan Bahasa (Hanya definisi dasar, tanpa menu)
[languages.id]
    languageName = "Bahasa Indonesia"
    title = "eduEasy Berita"
    weight = 1
    contentDir = "content"

# Parameter Website
[params]
    mainSections = ["post"]
    
    [params.sidebar]
        emoji = "ğŸ¥"
        subtitle = "Portal Informasi Pendidikan & Teknologi Terkini."
