# Ganti baseurl dengan alamat Netlify Anda
baseurl      = "https://berita.edueasy.id/"
languageCode = "id"
title        = "eduEasy Berita"

# Theme i18n support
defaultContentLanguage = "id"

hasCJKLanguage = false

# Kosongkan agar tidak muncul komentar demo
disqusShortname = ""

[pagination]
    pagerSize = 5
