# Ganti baseurl dengan alamat Netlify Anda
baseurl      = "https://edueasy-berita.netlify.app/"
languageCode = "id"
title        = "EduEasy Berita"

# Theme i18n support
defaultContentLanguage = "id"

hasCJKLanguage = false

# Kosongkan agar tidak muncul komentar demo
disqusShortname = ""

[pagination]
    pagerSize = 5
