baseURL = "https://berita.edueasy.id/"
languageCode = "id"
title = "eduEasy Berita"

# Pengaturan Bahasa Indonesia
[languages.id]
    languageName = "Bahasa Indonesia"
    title = "eduEasy Berita"
    weight = 1
    contentDir = "content"

[params]
    # Agar artikel muncul di halaman depan
    mainSections = ["post"]
    
    [params.sidebar]
        emoji = "ğŸ¥"
        subtitle = "Portal Informasi Pendidikan & Teknologi Terkini."
