baseURL = "https://berita.edueasy.id/"
languageCode = "id"
title = "eduEasy Berita"

# --- PERBAIKAN DI SINI ---
# Kita gunakan "module" agar Netlify mendownload tema otomatis
[module]
  [[module.imports]]
    path = "github.com/CaiJimmy/hugo-theme-stack/v3"

# Pengaturan Bahasa Indonesia
[languages.id]
    languageName = "Bahasa Indonesia"
    title = "eduEasy Berita"
    weight = 1
    contentDir = "content"

[params]
    # Agar artikel muncul di halaman depan
    mainSections = ["post"]
    
    [params.sidebar]
        emoji = "üç•"
        subtitle = "Portal Informasi Pendidikan & Teknologi Terkini."
