baseURL = "https://berita.edueasy.id/"
languageCode = "id"
title = "eduEasy Berita"
theme = "hugo-theme-stack"

# Pengaturan Bahasa (Penting pengganti languages.toml)
[languages.id]
    languageName = "Bahasa Indonesia"
    title = "eduEasy Berita"
    weight = 1
    contentDir = "content"

[params]
    # Agar tidak error saat build
    mainSections = ["post"]
    
    [params.sidebar]
        emoji = "ğŸ¥"
        subtitle = "Portal Informasi Pendidikan & Teknologi Terkini."
