# File ini akan MENGGANTIKAN menu bawaan tema.
# Jadi "Links" tidak akan muncul karena tidak ditulis di sini.

[[main]]
    identifier = "back"
    name = "Kembali ke Utama"
    url = "https://edueasy.id/"
    weight = 4
    # Tanpa icon

# --- PENIMPA MENU LINKS ---
[[main]]
    identifier = "links"
    name = "Links"      # Kita namai dulu untuk memastikan ini tertimpa
    url = "#hidelinks"  # URL unik untuk target penghapusan
    weight = 999        # Taruh paling bawah
