# File ini akan MENGGANTIKAN menu bawaan tema.
# Jadi "Links" tidak akan muncul karena tidak ditulis di sini.

[[main]]
    identifier = "back"
    name = "Kembali ke Utama"
    url = "https://edueasy.id/"
    weight = 4
    # Tanpa icon
