[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
    [main.params]
        icon = "home"

[[main]]
    identifier = "archives"
    name = "Archives"
    url = "/archives/"
    weight = 2
    # Icon dihapus sementara agar tidak error

[[main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 3
    [main.params]
        icon = "search"

[[main]]
    identifier = "back"
    name = "Back"
    url = "https://edueasy.id/"
    weight = 4
    # Icon dihapus sementara agar tidak error
