# File ini akan MENGGANTIKAN menu bawaan tema.
# Jadi "Links" tidak akan muncul karena tidak ditulis di sini.

[[main]]
    identifier = "back"
    name = "Kembali ke Utama"
    url = "https://edueasy.id/"
    weight = 4
    # Tanpa icon

[[main]]
    identifier = "links"
    name = "Aplikasi"   # <--- Ganti "Links" jadi "Aplikasi" / "Portal"
    url = "/links/"
    weight = 5          # Atur posisi urutan menu
    pre = "server"      # Ganti ikon rantai jadi ikon server/list (opsional)
