# Menu Home (Icon home biasanya aman)
[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
    [main.params]
        icon = "home"

# Menu Archives (SAYA HAPUS ICON-NYA SUPAYA TIDAK ERROR)
[[main]]
    identifier = "archives"
    name = "Arsip"
    url = "/archives/"
    weight = 2

# Menu Search (Icon search biasanya aman)
[[main]]
    identifier = "search"
    name = "Cari"
    url = "/search/"
    weight = 3
    [main.params]
        icon = "search"

# Menu Kembali (Tanpa Icon)
[[main]]
    identifier = "back"
    name = "Kembali ke Utama"
    url = "https://edueasy.id/"
    weight = 4
